## Practical Mechine Learning Course Project Writeup

### Background
Using devices such as Jawbone Up, Nike FuelBand, and Fitbit it is now possible to collect a large amount of data about personal activity relatively inexpensively.
These type of devices are part of the quantified self movement – a group of enthusiasts who take measurements about themselves regularly to improve their health, to find patterns in their behavior, or because they are tech geeks.
One thing that people regularly do is quantify how much of a particular activity they do, but they rarely quantify how well they do it.
In this project, the goal will be to use data from accelerometers on the belt, forearm, arm, and dumbell of 6 participants.
They were asked to perform barbell lifts correctly and incorrectly in 5 different ways. 
More information is available from the website here: http://groupware.les.inf.puc-rio.br/har (see the section on the Weight Lifting Exercise Dataset).

### Download training and testing data files
```r 
download.file("http://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv", destfile = "pml-training.csv")
download.file("http://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv", destfile = "pml-testing.csv")
```

### Pre-processing data
The goal of pre-processing data is to obtain a set of concise predictors for the machine learning prediction. 
The data cleaning process apply to both training and testing data sets.

Read the raw data and set the classe as factor. 
```r
library(caret)
data <- read.csv("pml-training.csv", stringsAsFactors=FALSE)
data$classe <- as.factor(data$classe)
data_test <- read.csv("pml-testing.csv", stringsAsFactors=FALSE)
``` 

Then clean the data: 

a. Removing columns with features not related to precition outcomes (first 7 columns)
```r
data <- data[,-c(1:7)]
data_test <- data_test[,-c(1:7)]
```
b. Removing columns with too little data that are not valuable enough in prediction
```r
data <- data[,-nearZeroVar(data)]
data_test <- data_test[,-nearZeroVar(data_test)]
```
c. Removing columns with too many NAs (>90%)

function 1: 'def_NAs' define variables with na > 90% 
```r
def_NAs <- function(value){
        if(sum(is.na(value))/length(value) > 0.9){ # if vector is made of more than 90% NAs
                res <- TRUE;                             # return true
        }else{                                       # if it doesn't
                res <- FALSE;                            # return false
        }
        invisible(res);                              # return a invisible copy of the results
}
```
Apply the function on the pml-training data
```r
vars_90NAs <- sapply(data, def_NAs) # find columns with NA > 90%
data <- data[,!vars_90NAs] # no NA in data anymore in this case
```
Apply the function on the pml-testing data 
```r
vars_90NAs_test <- sapply(data_test, def_NAs) 
data_test <- data_test[,!vars_90NAs_test] 
```

### Prediction and Cross-validation

Split the cleaned training data into training and testing sets. 
Use "random forest" algorithm in caret package and all other variables in the training set in the model training.
Apply the modelFit on the testing set for cross-validation.
```r
inTrain <- createDataPartition(y=data$classe, p= 0.7, list=FALSE)
training <- data[inTrain,]
testing <- data[-inTrain,]
modelFit <- train(training$classe ~., data = training, method = "rf")
test <- predict(modelFit, newdata = testing)
confusionMatrix(testing$classe, test)
```
Results and analysis: 

The cross-validation shows the accuracy of this model is 0.9941. 
Therefore, the out of sample error is (1 - Accuracy) = 0.0059.
```r
Confusion Matrix and Statistics

          Reference
Prediction    A    B    C    D    E
         A 1674    0    0    0    0
         B    8 1129    2    0    0
         C    0    3 1016    7    0
         D    0    0   10  953    1
         E    0    0    2    2 1078

Overall Statistics
                                          
               Accuracy : 0.9941          
                 95% CI : (0.9917, 0.9959)
    No Information Rate : 0.2858          
    P-Value [Acc > NIR] : < 2.2e-16       
                                          
                  Kappa : 0.9925          
 Mcnemar's Test P-Value : NA              

Statistics by Class:

                     Class: A Class: B Class: C Class: D Class: E
Sensitivity            0.9952   0.9973   0.9864   0.9906   0.9991
Specificity            1.0000   0.9979   0.9979   0.9978   0.9992
Pos Pred Value         1.0000   0.9912   0.9903   0.9886   0.9963
Neg Pred Value         0.9981   0.9994   0.9971   0.9982   0.9998
Prevalence             0.2858   0.1924   0.1750   0.1635   0.1833
Detection Rate         0.2845   0.1918   0.1726   0.1619   0.1832
Detection Prevalence   0.2845   0.1935   0.1743   0.1638   0.1839
Balanced Accuracy      0.9976   0.9976   0.9922   0.9942   0.9991
```

### Final predictions on data_test from "pml-testing.csv" file
```r
prediction <- predict(modelFit, newdata = data_test)
prediction
 [1] B A B A A E D B A A B C B A E E A B B B
Levels: A B C D E
```
